name: unitig_caller_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python
  - pip
  - cmake
  - pybind11
  - zlib
  - bzip2
  - bifrost >=1.0.6
  - seqan3 >=3.1.0
  - pthread-stubs
