{% set version = "1.0.0" %}
{% set name = "unitig-caller" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/johnlees/{{ name|lower }}.git
  git_rev: f501ea2f0d06fb303b5d7a38ab9ec8d8c8863237

build:
  number: 0
  skip: True #  [osx]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - unitig_caller = unitig_caller.__main__:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - python >=3
  host:
    - python >=3
    - cmake
    - pybind11
  run:
    - mantis >=0.2.0
    - squeakr >=0.6

test:
  imports:
    - unitig_caller
    - map_strings

  commands:
    - unitig_caller --help

about:
  home: https://github.com/johnlees/unitig-caller
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Determines presence/absence of sequence elements from bacterial sequence data'

extra:
   skip-lints:
     - uses_git_url
